"""codegraph.arch_planner — Architecture decomposition engine.

Takes a SystemArchitecture definition and compares it against the actual
code graph to produce granular, agent-executable tasks. Bridges the gap
between high-level architecture goals and small code changes.

Pipeline:
    SystemArchitecture → compare with graph0/workflow → ArchPlan (tasks)

Task types generated:
    - create_module: a module file needs to be created
    - create_function: a function needs to be created in an existing module
    - connect_call: a call edge needs to be added between two functions
    - add_constraint: a forbidden dependency must be enforced
    - flag_violation: an existing edge violates a constraint
"""

from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

from codegraph.arch_schema import (
    ArchConstraint,
    ArchEdge,
    SystemArchitecture,
    SubsystemDef,
)
from codegraph.index import IndexStore
from codegraph.logging_config import get_logger
from codegraph.models.graph0 import Graph0

logger = get_logger("arch_planner")


# ── PlannedTask ────────────────────────────────────────────────────────


@dataclass
class PlannedTask:
    """A single granular task generated by the architecture planner."""

    task_type: str  # create_module, create_function, connect_call, add_constraint, flag_violation
    subsystem: str = ""
    module: str = ""
    function: str = ""
    source: str = ""
    target: str = ""
    reason: str = ""
    priority: int = 5

    def to_dict(self) -> Dict[str, Any]:
        d: Dict[str, Any] = {"task_type": self.task_type, "priority": self.priority}
        if self.subsystem:
            d["subsystem"] = self.subsystem
        if self.module:
            d["module"] = self.module
        if self.function:
            d["function"] = self.function
        if self.source:
            d["source"] = self.source
        if self.target:
            d["target"] = self.target
        if self.reason:
            d["reason"] = self.reason
        return d

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> PlannedTask:
        return cls(
            task_type=d["task_type"],
            subsystem=d.get("subsystem", ""),
            module=d.get("module", ""),
            function=d.get("function", ""),
            source=d.get("source", ""),
            target=d.get("target", ""),
            reason=d.get("reason", ""),
            priority=d.get("priority", 5),
        )


# ── CoverageResult ─────────────────────────────────────────────────────


@dataclass
class CoverageResult:
    """How much of the architecture already exists in the code."""

    total_modules: int = 0
    existing_modules: int = 0
    total_functions: int = 0
    existing_functions: int = 0
    total_edges: int = 0
    existing_edges: int = 0

    @property
    def module_coverage(self) -> float:
        return self.existing_modules / self.total_modules if self.total_modules else 1.0

    @property
    def function_coverage(self) -> float:
        return self.existing_functions / self.total_functions if self.total_functions else 1.0

    @property
    def edge_coverage(self) -> float:
        return self.existing_edges / self.total_edges if self.total_edges else 1.0

    @property
    def overall_coverage(self) -> float:
        parts = []
        if self.total_modules:
            parts.append(self.module_coverage)
        if self.total_functions:
            parts.append(self.function_coverage)
        if self.total_edges:
            parts.append(self.edge_coverage)
        return sum(parts) / len(parts) if parts else 1.0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "modules": {"total": self.total_modules, "existing": self.existing_modules,
                        "coverage": round(self.module_coverage, 3)},
            "functions": {"total": self.total_functions, "existing": self.existing_functions,
                          "coverage": round(self.function_coverage, 3)},
            "edges": {"total": self.total_edges, "existing": self.existing_edges,
                      "coverage": round(self.edge_coverage, 3)},
            "overall_coverage": round(self.overall_coverage, 3),
        }


# ── ArchPlan ───────────────────────────────────────────────────────────


@dataclass
class ArchPlan:
    """Complete architecture plan with decomposed tasks."""

    architecture_name: str = ""
    coverage: CoverageResult = field(default_factory=CoverageResult)
    missing_modules: List[str] = field(default_factory=list)
    missing_functions: List[Dict[str, str]] = field(default_factory=list)
    missing_connections: List[Dict[str, str]] = field(default_factory=list)
    constraint_violations: List[Dict[str, Any]] = field(default_factory=list)
    tasks: List[PlannedTask] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "architecture": self.architecture_name,
            "coverage": self.coverage.to_dict(),
            "missing_modules": self.missing_modules,
            "missing_functions": self.missing_functions,
            "missing_connections": self.missing_connections,
            "constraint_violations": self.constraint_violations,
            "tasks": [t.to_dict() for t in self.tasks],
            "task_count": len(self.tasks),
        }

    def format(self) -> str:
        lines = [
            f"Architecture Plan: {self.architecture_name}",
            f"  Overall coverage: {self.coverage.overall_coverage:.1%}",
            f"  Modules: {self.coverage.existing_modules}/{self.coverage.total_modules}",
            f"  Functions: {self.coverage.existing_functions}/{self.coverage.total_functions}",
            f"  Edges: {self.coverage.existing_edges}/{self.coverage.total_edges}",
        ]
        if self.missing_modules:
            lines.append(f"\nMissing modules ({len(self.missing_modules)}):")
            for m in self.missing_modules[:20]:
                lines.append(f"  - {m}")
        if self.missing_functions:
            lines.append(f"\nMissing functions ({len(self.missing_functions)}):")
            for f in self.missing_functions[:20]:
                lines.append(f"  - {f['module']}::{f['function']}")
        if self.missing_connections:
            lines.append(f"\nMissing connections ({len(self.missing_connections)}):")
            for c in self.missing_connections[:20]:
                lines.append(f"  - {c['source']} → {c['target']}")
        if self.constraint_violations:
            lines.append(f"\nConstraint violations ({len(self.constraint_violations)}):")
            for v in self.constraint_violations[:10]:
                lines.append(f"  [{v['constraint']['type']}] {v['source_file']} → {v['target_file']}")
        lines.append(f"\nTotal tasks: {len(self.tasks)}")
        by_type: Dict[str, int] = defaultdict(int)
        for t in self.tasks:
            by_type[t.task_type] += 1
        for tt, count in sorted(by_type.items()):
            lines.append(f"  {tt}: {count}")
        return "\n".join(lines)


# ── Planner Functions ──────────────────────────────────────────────────


def plan_architecture(
    arch: SystemArchitecture,
    graph0: Graph0,
    index: IndexStore,
) -> ArchPlan:
    """Compare architecture definition against actual code and generate tasks.

    Returns an ArchPlan containing coverage metrics and granular tasks
    that an agent can execute to bring the code closer to the architecture.
    """
    plan = ArchPlan(architecture_name=arch.name)

    # Build lookup structures from the actual code
    existing_files: Set[str] = {n.file for n in graph0.nodes}
    existing_nodes: Set[str] = {n.id for n in graph0.nodes}
    node_to_file: Dict[str, str] = {n.id: n.file for n in graph0.nodes}

    # Build actual edge set from index
    actual_edges: Set[Tuple[str, str]] = set()
    actual_file_edges: Set[Tuple[str, str]] = set()
    conn = index._get_conn()
    callee_rows = conn.execute("SELECT node_id, callee_id FROM callees").fetchall()
    for row in callee_rows:
        actual_edges.add((row[0], row[1]))
        src_file = node_to_file.get(row[0], "")
        tgt_file = node_to_file.get(row[1], "")
        if src_file and tgt_file and src_file != tgt_file:
            actual_file_edges.add((src_file, tgt_file))

    # ── Check modules ──
    expected_modules: List[str] = []
    for subsystem in arch.subsystems:
        for comp in subsystem.components:
            if comp.module:
                expected_modules.append(comp.module)

    plan.coverage.total_modules = len(expected_modules)
    for mod in expected_modules:
        if _module_exists(mod, existing_files):
            plan.coverage.existing_modules += 1
        else:
            plan.missing_modules.append(mod)
            subsys = _find_subsystem_for_module(arch, mod)
            plan.tasks.append(PlannedTask(
                task_type="create_module",
                subsystem=subsys,
                module=mod,
                reason=f"Architecture requires module {mod}",
                priority=2,
            ))

    # ── Check functions ──
    expected_functions: List[Tuple[str, str, str]] = []  # (subsys, module, func_name)
    for subsystem in arch.subsystems:
        for comp in subsystem.components:
            for fn in comp.functions:
                expected_functions.append((subsystem.name, comp.module, fn))

    plan.coverage.total_functions = len(expected_functions)
    for subsys_name, mod, fn_name in expected_functions:
        # Build expected node ID
        if "::" in fn_name:
            node_id = fn_name  # already qualified
        elif mod:
            node_id = f"{mod}::{fn_name}"
        else:
            node_id = fn_name

        if node_id in existing_nodes:
            plan.coverage.existing_functions += 1
        else:
            plan.missing_functions.append({"module": mod, "function": fn_name})
            plan.tasks.append(PlannedTask(
                task_type="create_function",
                subsystem=subsys_name,
                module=mod,
                function=fn_name,
                reason=f"Architecture requires function {fn_name} in {mod}",
                priority=3,
            ))

    # ── Check edges (inter-subsystem) ──
    _check_arch_edges(arch, graph0, actual_edges, actual_file_edges, existing_nodes, plan)

    # ── Check constraints ──
    if arch.constraints:
        violations = arch.get_constraint_violations(list(actual_file_edges))
        plan.constraint_violations = violations
        for v in violations:
            plan.tasks.append(PlannedTask(
                task_type="flag_violation",
                source=v["source_file"],
                target=v["target_file"],
                reason=f"Forbidden: {v['constraint'].get('reason', 'constraint violation')}",
                priority=1,
            ))

    # Sort tasks by priority
    plan.tasks.sort(key=lambda t: t.priority)

    logger.info(
        "Plan generated: %d tasks, %.1f%% coverage",
        len(plan.tasks),
        plan.coverage.overall_coverage * 100,
    )
    return plan


def _module_exists(module_path: str, existing_files: Set[str]) -> bool:
    """Check if a module path exists in the codebase."""
    if module_path in existing_files:
        return True
    # Check with .py extension
    if not module_path.endswith(".py"):
        if f"{module_path}.py" in existing_files:
            return True
    # Check if it's a package (directory with __init__.py)
    pkg_init = f"{module_path}/__init__.py"
    if pkg_init in existing_files:
        return True
    # Check prefix match for directories
    prefix = module_path.rstrip("/") + "/"
    return any(f.startswith(prefix) for f in existing_files)


def _find_subsystem_for_module(arch: SystemArchitecture, module: str) -> str:
    """Find which subsystem a module belongs to."""
    for s in arch.subsystems:
        for c in s.components:
            if c.module == module:
                return s.name
    return ""


def _check_arch_edges(
    arch: SystemArchitecture,
    graph0: Graph0,
    actual_edges: Set[Tuple[str, str]],
    actual_file_edges: Set[Tuple[str, str]],
    existing_nodes: Set[str],
    plan: ArchPlan,
) -> None:
    """Check architecture edges and subsystem internal edges."""
    # Build subsystem name → module paths mapping
    subsys_modules: Dict[str, Set[str]] = {}
    for s in arch.subsystems:
        subsys_modules[s.name] = set(s.module_paths)

    # Component name → module path
    comp_modules: Dict[str, str] = {}
    for s in arch.subsystems:
        for c in s.components:
            if c.module:
                comp_modules[c.name] = c.module

    # Check inter-subsystem edges
    total_arch_edges = 0
    existing_arch_edges = 0

    for edge in arch.edges:
        total_arch_edges += 1
        src_files = _resolve_target_files(edge.source, subsys_modules, comp_modules)
        tgt_files = _resolve_target_files(edge.target, subsys_modules, comp_modules)
        found = False
        for sf in src_files:
            for tf in tgt_files:
                if (sf, tf) in actual_file_edges:
                    found = True
                    break
            if found:
                break
        if found:
            existing_arch_edges += 1
        else:
            plan.missing_connections.append({
                "source": edge.source,
                "target": edge.target,
                "edge_type": edge.edge_type,
            })
            plan.tasks.append(PlannedTask(
                task_type="connect_call",
                source=edge.source,
                target=edge.target,
                reason=f"Architecture requires {edge.source} → {edge.target}",
                priority=3,
            ))

    # Check intra-subsystem edges
    for subsystem in arch.subsystems:
        for edge in subsystem.edges:
            total_arch_edges += 1
            src_mod = comp_modules.get(edge.source, edge.source)
            tgt_mod = comp_modules.get(edge.target, edge.target)
            if (src_mod, tgt_mod) in actual_file_edges:
                existing_arch_edges += 1
            else:
                plan.missing_connections.append({
                    "source": edge.source,
                    "target": edge.target,
                    "edge_type": edge.edge_type,
                    "subsystem": subsystem.name,
                })
                plan.tasks.append(PlannedTask(
                    task_type="connect_call",
                    subsystem=subsystem.name,
                    source=edge.source,
                    target=edge.target,
                    reason=f"Subsystem {subsystem.name} requires {edge.source} → {edge.target}",
                    priority=4,
                ))

    plan.coverage.total_edges = total_arch_edges
    plan.coverage.existing_edges = existing_arch_edges


def _resolve_target_files(
    name: str,
    subsys_modules: Dict[str, Set[str]],
    comp_modules: Dict[str, str],
) -> List[str]:
    """Resolve a subsystem/component name to file paths."""
    if name in subsys_modules:
        return list(subsys_modules[name])
    if name in comp_modules:
        return [comp_modules[name]]
    return [name]


def plan_to_agent_response(plan: ArchPlan, graph_version: int) -> Dict[str, Any]:
    """Convert an ArchPlan to agent_response.json format.

    Only includes tasks that map to repair actions codegraph can apply:
    connect_call and flag_for_human_review.
    """
    repairs: List[Dict[str, Any]] = []

    for task in plan.tasks:
        if task.task_type == "connect_call" and task.source and task.target:
            repairs.append({
                "node": task.source,
                "action": "connect_call",
                "target": task.target,
                "reason": task.reason,
            })
        elif task.task_type == "flag_violation":
            repairs.append({
                "node": task.source,
                "action": "flag_for_human_review",
                "target": task.target,
                "reason": task.reason,
            })
        elif task.task_type in ("create_module", "create_function"):
            repairs.append({
                "node": task.module or task.function,
                "action": "flag_for_human_review",
                "target": "",
                "reason": task.reason,
            })

    return {
        "cycle": 0,
        "graph_version": graph_version,
        "intents": [],
        "repairs": repairs,
    }
