"""codegraph.copilot_context — Copilot context generator.

Generates a comprehensive context file that Copilot reads before
making any architecture decisions. This prevents Copilot from guessing
about architecture — it always has the full picture.

Output: .codegraph/context/copilot_context.json

Contents:
  - System architecture (subsystems, edges, constraints)
  - Active policy rules (suggested_workflow)
  - Current architecture health metrics
  - Active tasks
  - Target architecture (if any)
  - Drift status
  - Recent decisions from architecture memory
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

from codegraph.arch_schema import SystemArchitecture
from codegraph.logging_config import get_logger

logger = get_logger("copilot_context")

CONTEXT_DIR = "context"
CONTEXT_FILE = "copilot_context.json"


# ── Context Sections ──────────────────────────────────────────────────


@dataclass
class SubsystemSummary:
    """Summary of a subsystem for context."""

    name: str
    description: str = ""
    component_count: int = 0
    module_paths: List[str] = field(default_factory=list)
    allowed_dependencies: List[str] = field(default_factory=list)
    forbidden_dependencies: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "name": self.name,
            "description": self.description,
            "component_count": self.component_count,
            "modules": self.module_paths,
            "allowed_deps": self.allowed_dependencies,
            "forbidden_deps": self.forbidden_dependencies,
        }


@dataclass
class CopilotContext:
    """Complete context package for Copilot decision-making.

    Generated by build_copilot_context() and saved to
    .codegraph/context/copilot_context.json.
    """

    subsystems: List[SubsystemSummary] = field(default_factory=list)
    constraints: List[Dict[str, str]] = field(default_factory=list)
    policy_rules: List[Dict[str, Any]] = field(default_factory=list)
    active_tasks: List[Dict[str, Any]] = field(default_factory=list)
    health_summary: Dict[str, Any] = field(default_factory=dict)
    target_summary: Dict[str, Any] = field(default_factory=dict)
    drift_summary: Dict[str, Any] = field(default_factory=dict)
    recent_decisions: List[Dict[str, Any]] = field(default_factory=list)
    architecture_smells: List[Dict[str, Any]] = field(default_factory=list)
    architecture_score: float = 0.0
    architecture_grade: str = ""
    active_policies: List[Dict[str, Any]] = field(default_factory=list)
    recommended_refactors: List[Dict[str, Any]] = field(default_factory=list)
    strategy_rankings: List[Dict[str, Any]] = field(default_factory=list)
    graph_version: int = 0
    node_count: int = 0
    edge_count: int = 0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "graph_version": self.graph_version,
            "graph_stats": {
                "nodes": self.node_count,
                "edges": self.edge_count,
            },
            "architecture": {
                "subsystems": [s.to_dict() for s in self.subsystems],
                "constraints": self.constraints,
                "score": self.architecture_score,
                "grade": self.architecture_grade,
            },
            "architecture_smells": self.architecture_smells,
            "active_policies": self.active_policies,
            "policy_rules": self.policy_rules,
            "active_tasks": self.active_tasks,
            "health": self.health_summary,
            "target": self.target_summary,
            "drift": self.drift_summary,
            "recent_decisions": self.recent_decisions,
            "recommended_refactors": self.recommended_refactors,
            "strategy_rankings": self.strategy_rankings,
        }

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> CopilotContext:
        arch = d.get("architecture", {})
        subsystems = [
            SubsystemSummary(
                name=s.get("name", ""),
                description=s.get("description", ""),
                component_count=s.get("component_count", 0),
                module_paths=s.get("modules", []),
                allowed_dependencies=s.get("allowed_deps", []),
                forbidden_dependencies=s.get("forbidden_deps", []),
            )
            for s in arch.get("subsystems", [])
        ]
        stats = d.get("graph_stats", {})
        return cls(
            subsystems=subsystems,
            constraints=arch.get("constraints", []),
            policy_rules=d.get("policy_rules", []),
            active_tasks=d.get("active_tasks", []),
            health_summary=d.get("health", {}),
            target_summary=d.get("target", {}),
            drift_summary=d.get("drift", {}),
            recent_decisions=d.get("recent_decisions", []),
            architecture_smells=d.get("architecture_smells", []),
            architecture_score=arch.get("score", 0.0),
            architecture_grade=arch.get("grade", ""),
            active_policies=d.get("active_policies", []),
            recommended_refactors=d.get("recommended_refactors", []),
            strategy_rankings=d.get("strategy_rankings", []),
            graph_version=d.get("graph_version", 0),
            node_count=stats.get("nodes", 0),
            edge_count=stats.get("edges", 0),
        )

    def save(self, project_root: Path) -> Path:
        path = project_root / ".codegraph" / CONTEXT_DIR / CONTEXT_FILE
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            json.dumps(self.to_dict(), indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        logger.info("Saved copilot context → %s", path)
        return path

    @classmethod
    def load(cls, project_root: Path) -> Optional[CopilotContext]:
        path = project_root / ".codegraph" / CONTEXT_DIR / CONTEXT_FILE
        if not path.exists():
            return None
        text = path.read_text(encoding="utf-8")
        return cls.from_dict(json.loads(text))

    def format(self) -> str:
        lines = ["Copilot Context"]
        lines.append(f"  Graph: v{self.graph_version} "
                      f"({self.node_count} nodes, {self.edge_count} edges)")
        lines.append(f"  Subsystems: {len(self.subsystems)}")
        lines.append(f"  Constraints: {len(self.constraints)}")
        lines.append(f"  Policy rules: {len(self.policy_rules)}")
        lines.append(f"  Active tasks: {len(self.active_tasks)}")
        if self.architecture_grade:
            lines.append(f"  Architecture: {self.architecture_grade}"
                         f"({self.architecture_score:.0%})")
        if self.health_summary:
            score = self.health_summary.get("score", "?")
            lines.append(f"  Health score: {score}")
        if self.target_summary:
            lines.append(f"  Target: {self.target_summary.get('description', 'active')}")
        if self.drift_summary:
            drift = self.drift_summary.get("drift_score", 0)
            lines.append(f"  Drift: {drift:.1%}")
        if self.recent_decisions:
            lines.append(f"  Recent decisions: {len(self.recent_decisions)}")

        if self.architecture_smells:
            lines.append(f"\nArchitecture Smells ({len(self.architecture_smells)}):")
            for s in self.architecture_smells[:10]:
                lines.append(f"  ⚠ {s.get('smell_type', '?')}: "
                             f"{s.get('description', '')}")

        if self.active_policies:
            lines.append(f"\nActive Policies ({len(self.active_policies)}):")
            for p in self.active_policies:
                lines.append(f"  [{p.get('policy_id', '?')}] {p.get('name', '')}"
                             f" ({p.get('action', 'warn')})")

        if self.recommended_refactors:
            lines.append(f"\nRecommended Refactors ({len(self.recommended_refactors)}):")
            for r in self.recommended_refactors[:5]:
                lines.append(f"  → {r.get('strategy', '?')}: "
                             f"{', '.join(r.get('target_modules', []))}")

        if self.strategy_rankings:
            lines.append(f"\nStrategy Rankings:")
            for sr in self.strategy_rankings[:5]:
                lines.append(f"  {sr.get('strategy', '?')}: "
                             f"{sr.get('effectiveness', 0):.0%} effective")

        lines.append("\nSubsystem Map:")
        for s in self.subsystems:
            deps = ", ".join(s.allowed_dependencies) if s.allowed_dependencies else "none"
            lines.append(f"  {s.name} ({s.component_count} components) → {deps}")
            if s.forbidden_dependencies:
                forbidden = ", ".join(s.forbidden_dependencies)
                lines.append(f"    FORBIDDEN → {forbidden}")

        return "\n".join(lines)


# ── Context Building ──────────────────────────────────────────────────


def build_copilot_context(
    project_root: Path,
    *,
    include_tasks: bool = True,
    include_health: bool = True,
    include_target: bool = True,
    include_drift: bool = True,
    include_decisions: bool = True,
    max_decisions: int = 10,
) -> CopilotContext:
    """Build comprehensive context for Copilot from .codegraph data.

    Reads all available .codegraph files and assembles a complete
    context object. Missing files are silently skipped.
    """
    ctx = CopilotContext()

    # 1. Architecture definition
    arch = SystemArchitecture.load(project_root)
    if arch:
        _populate_architecture(ctx, arch)

    # 2. Graph stats
    _populate_graph_stats(ctx, project_root)

    # 3. Policy rules
    _populate_policy_rules(ctx, project_root)

    # 4. Active tasks
    if include_tasks:
        _populate_tasks(ctx, project_root)

    # 5. Health summary
    if include_health:
        _populate_health(ctx, project_root)

    # 6. Target architecture
    if include_target:
        _populate_target(ctx, project_root)

    # 7. Drift status
    if include_drift:
        _populate_drift(ctx, project_root)

    # 8. Recent decisions
    if include_decisions:
        _populate_decisions(ctx, project_root, max_decisions)

    # 9. Architecture smells
    _populate_smells(ctx, project_root)

    # 10. Active architecture policies
    _populate_arch_policies(ctx, project_root)

    # 11. Recommended refactors from arch-search
    _populate_refactors(ctx, project_root)

    # 12. Strategy rankings from memory intelligence
    _populate_strategy_rankings(ctx, project_root)

    return ctx


# ── Internal Populators ───────────────────────────────────────────────


def _populate_architecture(
    ctx: CopilotContext,
    arch: SystemArchitecture,
) -> None:
    """Populate context with architecture info."""
    # Build allowed and forbidden edges per subsystem
    allowed_map: Dict[str, List[str]] = {}
    for edge in arch.edges:
        allowed_map.setdefault(edge.source, []).append(edge.target)

    forbidden_map: Dict[str, List[str]] = {}
    for c in arch.constraints:
        if c.constraint_type == "forbidden":
            forbidden_map.setdefault(c.source, []).append(c.target)

    for sub in arch.subsystems:
        ctx.subsystems.append(SubsystemSummary(
            name=sub.name,
            description=sub.description,
            component_count=len(sub.components),
            module_paths=sub.module_paths,
            allowed_dependencies=allowed_map.get(sub.name, []),
            forbidden_dependencies=forbidden_map.get(sub.name, []),
        ))

    ctx.constraints = [c.to_dict() for c in arch.constraints]


def _populate_graph_stats(
    ctx: CopilotContext,
    project_root: Path,
) -> None:
    """Populate graph version and stats from graph0.json."""
    graph0_path = project_root / ".codegraph" / "graphs" / "graph0.json"
    if not graph0_path.exists():
        return
    try:
        data = json.loads(graph0_path.read_text(encoding="utf-8"))
        ctx.graph_version = data.get("graph_version", 0)
        ctx.node_count = len(data.get("nodes", []))
    except (json.JSONDecodeError, OSError):
        pass

    workflow_path = project_root / ".codegraph" / "workflow" / "workflow.json"
    if workflow_path.exists():
        try:
            wf_data = json.loads(workflow_path.read_text(encoding="utf-8"))
            ctx.edge_count = len(wf_data.get("edges", []))
        except (json.JSONDecodeError, OSError):
            pass


def _populate_policy_rules(
    ctx: CopilotContext,
    project_root: Path,
) -> None:
    """Populate active policy rules from suggested_workflow.json."""
    sw_path = (project_root / ".codegraph" / "workflow"
               / "suggested_workflow.json")
    if not sw_path.exists():
        return
    try:
        data = json.loads(sw_path.read_text(encoding="utf-8"))
        rules = data.get("rules", [])
        # Include only active rules, summarized
        for rule in rules:
            ctx.policy_rules.append({
                "id": rule.get("id", ""),
                "type": rule.get("type", ""),
                "source": rule.get("source", ""),
                "target": rule.get("target", ""),
                "reason": rule.get("reason", ""),
            })
    except (json.JSONDecodeError, OSError):
        pass


def _populate_tasks(
    ctx: CopilotContext,
    project_root: Path,
) -> None:
    """Populate active tasks from tasks.json."""
    tasks_path = project_root / ".codegraph" / "tasks" / "tasks.json"
    if not tasks_path.exists():
        return
    try:
        data = json.loads(tasks_path.read_text(encoding="utf-8"))
        tasks = data.get("tasks", [])
        for task in tasks:
            ctx.active_tasks.append({
                "type": task.get("type", ""),
                "priority": task.get("priority", 10),
                "node_count": len(task.get("nodes", [])),
            })
    except (json.JSONDecodeError, OSError):
        pass


def _populate_health(
    ctx: CopilotContext,
    project_root: Path,
) -> None:
    """Populate health summary from latest health data."""
    health_path = project_root / ".codegraph" / "architecture" / "health.json"
    if not health_path.exists():
        return
    try:
        data = json.loads(health_path.read_text(encoding="utf-8"))
        ctx.health_summary = {
            "score": data.get("overall_score", 0),
            "grade": data.get("overall_grade", "?"),
        }
    except (json.JSONDecodeError, OSError):
        pass


def _populate_target(
    ctx: CopilotContext,
    project_root: Path,
) -> None:
    """Populate target architecture summary."""
    target_path = (project_root / ".codegraph" / "workflow"
                   / "target_workflow.json")
    if not target_path.exists():
        return
    try:
        data = json.loads(target_path.read_text(encoding="utf-8"))
        ctx.target_summary = {
            "description": data.get("description", ""),
            "target_edges": len(data.get("edges", [])),
            "target_nodes": len(data.get("nodes", [])),
        }
    except (json.JSONDecodeError, OSError):
        pass


def _populate_drift(
    ctx: CopilotContext,
    project_root: Path,
) -> None:
    """Populate drift summary from drift report."""
    drift_path = (project_root / ".codegraph" / "architecture"
                  / "drift_report.json")
    if not drift_path.exists():
        return
    try:
        data = json.loads(drift_path.read_text(encoding="utf-8"))
        ctx.drift_summary = {
            "has_drift": data.get("has_drift", False),
            "drift_score": data.get("drift_score", 0),
            "findings": data.get("summary", {}).get("total_findings", 0),
        }
    except (json.JSONDecodeError, OSError):
        pass


def _populate_decisions(
    ctx: CopilotContext,
    project_root: Path,
    max_decisions: int,
) -> None:
    """Populate recent architecture decisions from memory."""
    decisions_path = (project_root / ".codegraph" / "memory"
                      / "decisions.json")
    if not decisions_path.exists():
        return
    try:
        data = json.loads(decisions_path.read_text(encoding="utf-8"))
        decisions = data if isinstance(data, list) else data.get("decisions", [])
        # Take most recent decisions
        for d in decisions[-max_decisions:]:
            ctx.recent_decisions.append({
                "id": d.get("decision_id", ""),
                "decision": d.get("decision", ""),
                "result": d.get("result", ""),
            })
    except (json.JSONDecodeError, OSError):
        pass


def _populate_smells(
    ctx: CopilotContext,
    project_root: Path,
) -> None:
    """Populate architecture smells from advisor data."""
    advice_path = (project_root / ".codegraph" / "architecture"
                   / "architecture_advice.json")
    if not advice_path.exists():
        return
    try:
        data = json.loads(advice_path.read_text(encoding="utf-8"))
        ctx.architecture_score = data.get("score", 0.0)
        ctx.architecture_grade = data.get("grade", "")
        for smell in data.get("smells", []):
            ctx.architecture_smells.append({
                "smell_type": smell.get("smell_type", ""),
                "severity": smell.get("severity", "info"),
                "description": smell.get("description", ""),
                "target": smell.get("target", ""),
            })
    except (json.JSONDecodeError, OSError):
        pass


def _populate_arch_policies(
    ctx: CopilotContext,
    project_root: Path,
) -> None:
    """Populate active architecture policies."""
    policy_path = (project_root / ".codegraph" / "policies"
                   / "architecture_policies.json")
    if not policy_path.exists():
        return
    try:
        data = json.loads(policy_path.read_text(encoding="utf-8"))
        for p in data.get("policies", []):
            if p.get("enabled", True):
                ctx.active_policies.append({
                    "policy_id": p.get("policy_id", ""),
                    "name": p.get("name", ""),
                    "policy_type": p.get("policy_type", ""),
                    "action": p.get("action", "warn"),
                    "rule": p.get("rule", ""),
                })
    except (json.JSONDecodeError, OSError):
        pass


def _populate_refactors(
    ctx: CopilotContext,
    project_root: Path,
) -> None:
    """Populate recommended refactors from arch-search results."""
    search_path = (project_root / ".codegraph" / "planning"
                   / "arch_search.json")
    if not search_path.exists():
        return
    try:
        data = json.loads(search_path.read_text(encoding="utf-8"))
        for cand in data.get("candidates", []):
            ctx.recommended_refactors.append({
                "strategy": cand.get("strategy", ""),
                "target_modules": cand.get("target_modules", []),
                "predicted_score": cand.get("predicted_score", 0.0),
                "discard_reason": cand.get("discard_reason", ""),
            })
    except (json.JSONDecodeError, OSError):
        pass


def _populate_strategy_rankings(
    ctx: CopilotContext,
    project_root: Path,
) -> None:
    """Populate strategy effectiveness rankings from memory intelligence."""
    try:
        from codegraph.arch_memory_intelligence import get_strategy_ranking
        scores = get_strategy_ranking(project_root)
        for s in scores[:10]:
            ctx.strategy_rankings.append(s.to_dict())
    except (ImportError, Exception):
        pass
