"""codegraph.reactive_server — Push-model Reactive Intelligence Loop.

Architecture:

    File System  →  FileWatcher  →  ReactiveServer  →  PromptEngine  →  FeedbackWriter
                  (watchdog/poll)    (orchestrate)      (classify)       (deliver)

The server watches for file changes, runs the intelligence loop on
affected files, generates short/actionable/contextual prompts, and
writes feedback to:
    - `.codegraph/feedback.md` (for Copilot / editors to read)
    - terminal (for human visibility)

Prompt Types:
    1. ViolationPrompt   — architecture boundary crossed
    2. DecisionPrompt    — pattern match / memory-influenced advice
    3. RiskPrompt        — failure propagation / simulation warning
    4. OptimizationPrompt — better alternative found

File Watching:
    Prefers watchdog (OS-level inotify/FSEvents/ReadDirectoryChangesW) when
    available (``pip install codegraph[watch]``). Falls back to polling when
    watchdog is not installed. Both expose the same ``FileWatcher`` API so
    the rest of the server is unchanged.

CLI: ``codegraph server [--interval N] [--json] [--quiet]``
"""

from __future__ import annotations

import json
import os
import queue
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Set

from codegraph.logging_config import get_logger

logger = get_logger("reactive_server")

# Detect optional watchdog dependency
try:
    from watchdog.events import FileSystemEvent, FileSystemEventHandler
    from watchdog.observers import Observer as _WatchdogObserver

    _WATCHDOG_AVAILABLE = True
except ImportError:  # pragma: no cover
    _WATCHDOG_AVAILABLE = False

# ═══════════════════════════════════════════════════════════════════════
# 1. Prompt Engine — Classify and Generate
# ═══════════════════════════════════════════════════════════════════════

PROMPT_VIOLATION = "violation"
PROMPT_DECISION = "decision"
PROMPT_RISK = "risk"
PROMPT_OPTIMIZATION = "optimization"
PROMPT_INFO = "info"


@dataclass
class PromptContext:
    """Linked context for a prompt — affected modules, paths, subsystem."""

    affected_modules: List[str] = field(default_factory=list)
    path: str = ""  # dependency path, e.g. "A → B → C"
    subsystem: str = ""
    fan_in: int = 0
    fan_out: int = 0

    def to_dict(self) -> Dict[str, Any]:
        d: Dict[str, Any] = {}
        if self.affected_modules:
            d["affected_modules"] = self.affected_modules
        if self.path:
            d["path"] = self.path
        if self.subsystem:
            d["subsystem"] = self.subsystem
        if self.fan_in:
            d["fan_in"] = self.fan_in
        if self.fan_out:
            d["fan_out"] = self.fan_out
        return d

    def format_markdown(self) -> str:
        lines: List[str] = []
        if self.affected_modules:
            lines.append(f"- Affected modules: {', '.join(self.affected_modules)}")
        if self.path:
            lines.append(f"- Path: {self.path}")
        if self.subsystem:
            lines.append(f"- Subsystem: {self.subsystem}")
        if self.fan_in or self.fan_out:
            lines.append(f"- Fan-in: {self.fan_in}, Fan-out: {self.fan_out}")
        return "\n".join(lines)


@dataclass
class ReactivePrompt:
    """A single feedback prompt generated by the reactive loop.

    Designed as a *behavioral control signal* — not just information,
    but a directive that tells Copilot exactly what to do next.
    """

    prompt_type: str = PROMPT_INFO  # violation | decision | risk | optimization | info
    severity: str = "low"  # low | medium | high | critical
    priority: str = "LOW"  # LOW | MEDIUM | HIGH
    blocking: bool = False  # True = must resolve before proceeding
    title: str = ""
    body: str = ""
    target: str = ""
    suggested_commands: List[str] = field(default_factory=list)
    context: PromptContext = field(default_factory=PromptContext)
    timestamp: str = ""

    def to_dict(self) -> Dict[str, Any]:
        d: Dict[str, Any] = {
            "prompt_type": self.prompt_type,
            "severity": self.severity,
            "priority": self.priority,
            "blocking": self.blocking,
            "title": self.title,
            "body": self.body,
            "target": self.target,
            "suggested_commands": self.suggested_commands,
            "timestamp": self.timestamp,
        }
        ctx = self.context.to_dict()
        if ctx:
            d["context"] = ctx
        return d

    def format_markdown(self) -> str:
        """Render as behavioral control Markdown — ACTION REQUIRED format."""
        icon = {
            PROMPT_VIOLATION: "\u2757",   # ❗
            PROMPT_RISK: "\u26a0\ufe0f",  # ⚠️
            PROMPT_OPTIMIZATION: "\U0001f3af",  # 🎯
            PROMPT_DECISION: "\U0001f9e0",  # 🧠
            PROMPT_INFO: "\u2139\ufe0f",  # ℹ️
        }.get(self.prompt_type, "\u2139\ufe0f")

        # Priority + blocking header
        if self.blocking:
            header = f"{icon} **{self.priority} PRIORITY (BLOCKING)** — {self.title}"
        else:
            header = f"{icon} **{self.priority} PRIORITY** — {self.title}"

        lines = [header]

        if self.body:
            lines.append(f"\n{self.body}")

        # Context linking
        ctx_md = self.context.format_markdown()
        if ctx_md:
            lines.append(f"\n**Context:**\n{ctx_md}")

        # Behavioral control: mandatory next steps
        if self.suggested_commands:
            if self.blocking:
                lines.append("\n**NEXT STEP (MANDATORY):**")
            else:
                lines.append("\n**Suggested action:**")
            for i, cmd in enumerate(self.suggested_commands, 1):
                lines.append(f"{i}. `{cmd}`")

        if self.blocking:
            lines.append("\n> **DO NOT** proceed without resolving this.")

        lines.append("")
        return "\n".join(lines)

    def format_terminal(self) -> str:
        """Render as concise terminal output (no Markdown)."""
        prefix = {
            PROMPT_VIOLATION: "[VIOLATION]",
            PROMPT_RISK: "[RISK]",
            PROMPT_OPTIMIZATION: "[OPTIMIZE]",
            PROMPT_DECISION: "[DECISION]",
            PROMPT_INFO: "[INFO]",
        }.get(self.prompt_type, "[INFO]")

        blocking_tag = " BLOCKING" if self.blocking else ""
        parts = [f"{prefix} [{self.priority}{blocking_tag}] {self.title}"]
        if self.body:
            parts.append(f"  {self.body}")
        if self.context.affected_modules:
            parts.append(f"  Affects: {', '.join(self.context.affected_modules)}")
        if self.context.subsystem:
            parts.append(f"  Subsystem: {self.context.subsystem}")
        for cmd in self.suggested_commands:
            parts.append(f"  -> {cmd}")
        if self.blocking:
            parts.append("  !! MUST RESOLVE BEFORE PROCEEDING")
        return "\n".join(parts)


class PromptEngine:
    """Analyze intelligence results and generate typed prompts.

    Computes priority (HIGH/MEDIUM/LOW), blocking flag, and context
    linking (affected modules, paths, subsystem) for each prompt.
    """

    @staticmethod
    def _build_context(
        focus: Optional[Dict[str, Any]] = None,
    ) -> PromptContext:
        """Extract context-linking data from focus dict."""
        ctx = PromptContext()
        if not focus:
            return ctx
        # Affected modules: callees from focus
        callees = focus.get("callees", [])
        callers = focus.get("callers", [])
        ctx.affected_modules = list(dict.fromkeys(callers[:5] + callees[:5]))
        ctx.subsystem = focus.get("subsystem", "")
        ctx.fan_in = focus.get("fan_in", 0)
        ctx.fan_out = focus.get("fan_out", 0)
        # Build path from edges if available
        edges = focus.get("edges", [])
        if edges:
            path_parts: List[str] = []
            for e in edges[:4]:
                src = e.get("source", "").split("::")[-1]
                tgt = e.get("target", "").split("::")[-1]
                if src and tgt:
                    if not path_parts:
                        path_parts.append(src)
                    path_parts.append(tgt)
            if path_parts:
                ctx.path = " \u2192 ".join(dict.fromkeys(path_parts))
        return ctx

    @staticmethod
    def _compute_priority(
        prompt_type: str, severity: str, blocking: bool
    ) -> str:
        """Compute priority from type + severity."""
        if blocking:
            return "HIGH"
        if severity in ("critical", "high"):
            return "HIGH"
        if severity == "medium":
            return "MEDIUM"
        if prompt_type == PROMPT_VIOLATION:
            return "HIGH"
        return "LOW"

    @staticmethod
    def generate(
        target: str,
        *,
        focus: Optional[Dict[str, Any]] = None,
        decision: Optional[Dict[str, Any]] = None,
        simulation: Optional[Dict[str, Any]] = None,
        deep_sim: Optional[Dict[str, Any]] = None,
        timestamp: str = "",
    ) -> List[ReactivePrompt]:
        """Generate prompts from intelligence loop results.

        Takes the dict outputs of focus_context, decide, copilot_loop.
        Returns a list of prompts sorted by severity (critical first).
        """
        prompts: List[ReactivePrompt] = []

        # Build context once from focus data
        ctx = PromptEngine._build_context(focus)

        # --- 1. Violation prompts ---
        if focus:
            violations = focus.get("violations", [])
            for v in violations:
                msg = v if isinstance(v, str) else str(v)
                _blk = True
                prompts.append(ReactivePrompt(
                    prompt_type=PROMPT_VIOLATION,
                    severity="high",
                    priority=PromptEngine._compute_priority(PROMPT_VIOLATION, "high", _blk),
                    blocking=_blk,
                    title=f"Violation in {target}",
                    body=msg,
                    target=target,
                    suggested_commands=[
                        f"codegraph focus {target} --json",
                        f"codegraph decide {target} --json",
                    ],
                    context=ctx,
                    timestamp=timestamp,
                ))

            # Smells → optimization prompts
            smells = focus.get("smells", [])
            for smell in smells:
                smell_type = smell.get("smell_type", "unknown")
                desc = smell.get("description", "")
                sev = "medium" if smell.get("severity") == "medium" else "low"
                prompts.append(ReactivePrompt(
                    prompt_type=PROMPT_OPTIMIZATION,
                    severity=sev,
                    priority=PromptEngine._compute_priority(PROMPT_OPTIMIZATION, sev, False),
                    blocking=False,
                    title=f"Smell ({smell_type}) in {target}",
                    body=desc,
                    target=target,
                    suggested_commands=[
                        f"codegraph decide {target} --json",
                        f"codegraph scenario --components {target} --json",
                    ],
                    context=ctx,
                    timestamp=timestamp,
                ))

        # --- 2. Decision prompts ---
        if decision:
            action = decision.get("action", "")
            confidence = decision.get("confidence", 0)
            risk = decision.get("risk", "low")
            reason = decision.get("reason", "")

            if action == "fix_violations":
                _sev = "high" if risk == "high" else "medium"
                _blk = risk == "high"
                prompts.append(ReactivePrompt(
                    prompt_type=PROMPT_DECISION,
                    severity=_sev,
                    priority=PromptEngine._compute_priority(PROMPT_DECISION, _sev, _blk),
                    blocking=_blk,
                    title=f"Decision: {action} ({target})",
                    body=f"{reason}\nConfidence: {confidence:.0%}, Risk: {risk}",
                    target=target,
                    suggested_commands=decision.get("next_steps", []),
                    context=ctx,
                    timestamp=timestamp,
                ))
            elif action != "safe_to_edit":
                _sev = "medium" if risk != "low" else "low"
                prompts.append(ReactivePrompt(
                    prompt_type=PROMPT_DECISION,
                    severity=_sev,
                    priority=PromptEngine._compute_priority(PROMPT_DECISION, _sev, False),
                    blocking=False,
                    title=f"Decision: {action} ({target})",
                    body=f"{reason}\nConfidence: {confidence:.0%}",
                    target=target,
                    suggested_commands=decision.get("next_steps", []),
                    context=ctx,
                    timestamp=timestamp,
                ))

        # --- 3. Risk prompts (from simulation) ---
        if simulation:
            cycle_risk = simulation.get("cycle_risk", 0)
            coupling_delta = simulation.get("coupling_delta", 0)

            if cycle_risk > 0:
                _sev = "high" if cycle_risk > 2 else "medium"
                _blk = cycle_risk > 2
                prompts.append(ReactivePrompt(
                    prompt_type=PROMPT_RISK,
                    severity=_sev,
                    priority=PromptEngine._compute_priority(PROMPT_RISK, _sev, _blk),
                    blocking=_blk,
                    title=f"Cycle risk: {cycle_risk} new cycle(s)",
                    body=f"Simulation predicts {cycle_risk} cycle(s) if {target} is modified.",
                    target=target,
                    suggested_commands=[
                        f"codegraph copilot-loop {target} --simulate --json",
                    ],
                    context=ctx,
                    timestamp=timestamp,
                ))

            if coupling_delta > 0.05:
                prompts.append(ReactivePrompt(
                    prompt_type=PROMPT_RISK,
                    severity="medium",
                    priority=PromptEngine._compute_priority(PROMPT_RISK, "medium", False),
                    blocking=False,
                    title=f"Coupling increase: +{coupling_delta:.2f}",
                    body=f"Change to {target} increases coupling.",
                    target=target,
                    suggested_commands=[
                        f"codegraph focus {target} --json",
                    ],
                    context=ctx,
                    timestamp=timestamp,
                ))

        # --- 3b. Deep simulation risk prompts ---
        if deep_sim:
            failure_chains = deep_sim.get("failure_chains", [])
            if failure_chains:
                chain_count = len(failure_chains)
                preview = failure_chains[0] if failure_chains else ""
                _sev = "high" if chain_count >= 3 else "medium"
                _blk = chain_count >= 3
                prompts.append(ReactivePrompt(
                    prompt_type=PROMPT_RISK,
                    severity=_sev,
                    priority=PromptEngine._compute_priority(PROMPT_RISK, _sev, _blk),
                    blocking=_blk,
                    title=f"Failure propagation: {chain_count} chain(s)",
                    body=f"Example: {preview}" if preview else "",
                    target=target,
                    suggested_commands=[
                        f"codegraph copilot-loop {target} --simulate --json",
                    ],
                    context=ctx,
                    timestamp=timestamp,
                ))

            data_flow = deep_sim.get("data_flow_edges_affected", 0)
            if data_flow >= 3:
                prompts.append(ReactivePrompt(
                    prompt_type=PROMPT_RISK,
                    severity="medium",
                    priority=PromptEngine._compute_priority(PROMPT_RISK, "medium", False),
                    blocking=False,
                    title=f"Data flow impact: {data_flow} edge(s) affected",
                    body=f"Changes to {target} affect {data_flow} data flow edges.",
                    target=target,
                    suggested_commands=[
                        f"codegraph focus {target} --json",
                    ],
                    context=ctx,
                    timestamp=timestamp,
                ))

        # --- 4. Optimization prompts (from decision alternatives) ---
        if decision:
            for alt in decision.get("alternatives", []):
                alt_action = alt.get("action", "")
                alt_reason = alt.get("reason_rejected", "")
                if alt_action and "split" in alt_action.lower():
                    prompts.append(ReactivePrompt(
                        prompt_type=PROMPT_OPTIMIZATION,
                        severity="low",
                        priority="LOW",
                        blocking=False,
                        title=f"Alternative: {alt_action}",
                        body=f"Not chosen because: {alt_reason}",
                        target=target,
                        suggested_commands=[
                            f"codegraph scenario --components {target} --json",
                        ],
                        context=ctx,
                        timestamp=timestamp,
                    ))

        # Sort: HIGH blocking first, then by severity
        def _sort_key(p: ReactivePrompt) -> tuple:
            priority_order = {"HIGH": 0, "MEDIUM": 1, "LOW": 2}
            severity_order = {"critical": 0, "high": 1, "medium": 2, "low": 3}
            return (
                0 if p.blocking else 1,
                priority_order.get(p.priority, 3),
                severity_order.get(p.severity, 4),
            )

        prompts.sort(key=_sort_key)

        return prompts


# ═══════════════════════════════════════════════════════════════════════
# 2. Feedback Writer — Deliver Prompts
# ═══════════════════════════════════════════════════════════════════════

FEEDBACK_FILE = "feedback.md"


class FeedbackWriter:
    """Write prompts to .codegraph/feedback.md and optionally to a callback."""

    def __init__(
        self,
        project_root: Path,
        *,
        terminal_callback: Optional[Callable[[str], None]] = None,
        json_mode: bool = False,
        quiet: bool = False,
    ):
        self.project_root = project_root
        self.feedback_dir = project_root / ".codegraph"
        self.feedback_path = self.feedback_dir / FEEDBACK_FILE
        self.terminal_callback = terminal_callback
        self.json_mode = json_mode
        self.quiet = quiet

    def write(self, prompts: List[ReactivePrompt], *, append: bool = False) -> Path:
        """Write prompts to feedback.md and optionally echo to terminal.

        Prompts are grouped: BLOCKING items appear first under a
        dedicated header so Copilot sees them immediately.

        Returns the path to the feedback file.
        """
        self.feedback_dir.mkdir(parents=True, exist_ok=True)

        blocking = [p for p in prompts if p.blocking]
        non_blocking = [p for p in prompts if not p.blocking]

        # Build Markdown content
        lines: List[str] = []
        if not append:
            lines.append("# Codegraph Reactive Feedback\n")
            lines.append(
                "> Auto-generated by `codegraph server`. "
                "Read by Copilot for architecture-aware editing.\n"
            )

        if blocking:
            lines.append("## BLOCKING — Resolve Before Proceeding\n")
            for prompt in blocking:
                lines.append(prompt.format_markdown())
                lines.append("---\n")

        if non_blocking:
            if blocking:
                lines.append("## Advisory\n")
            for prompt in non_blocking:
                lines.append(prompt.format_markdown())
                lines.append("---\n")

        content = "\n".join(lines)

        # Write file
        mode = "a" if append else "w"
        with open(self.feedback_path, mode, encoding="utf-8") as f:
            f.write(content)

        # Terminal output
        if not self.quiet:
            for prompt in prompts:
                if self.json_mode:
                    text = json.dumps(prompt.to_dict(), indent=2)
                else:
                    text = prompt.format_terminal()

                if self.terminal_callback:
                    self.terminal_callback(text)
                else:
                    print(text)

        return self.feedback_path

    def write_json(self, prompts: List[ReactivePrompt]) -> Path:
        """Write prompts as JSON array to .codegraph/feedback.json."""
        json_path = self.feedback_dir / "feedback.json"
        data = [p.to_dict() for p in prompts]
        json_path.write_text(
            json.dumps(data, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        return json_path


# ═══════════════════════════════════════════════════════════════════════
# 3. File Watcher — Polling-based (no external deps)
# ═══════════════════════════════════════════════════════════════════════

DEFAULT_POLL_INTERVAL = 2.0  # seconds
DEBOUNCE_WINDOW = 1.0  # seconds — ignore rapid re-fires


@dataclass
class FileChange:
    """A detected file change."""

    path: str  # relative to project root
    change_type: str  # modified | created | deleted
    mtime: float = 0.0


class FileWatcher:
    """Poll-based Python file watcher.

    Scans project root for .py files, tracks mtime, detects changes.
    No external dependencies required.
    """

    def __init__(
        self,
        project_root: Path,
        *,
        interval: float = DEFAULT_POLL_INTERVAL,
        extensions: Optional[Set[str]] = None,
        exclude_dirs: Optional[Set[str]] = None,
    ):
        self.project_root = project_root
        self.interval = max(interval, 0.5)
        self.extensions = extensions or {".py"}
        self.exclude_dirs = exclude_dirs or {
            ".codegraph", "__pycache__", ".git", ".venv", "venv",
            "node_modules", ".tox", ".mypy_cache", ".pytest_cache",
            "dist", "build", ".eggs", "*.egg-info",
        }
        self._snapshot: Dict[str, float] = {}
        self._last_change_time: Dict[str, float] = {}
        self._running = False

    def _should_exclude(self, path: Path) -> bool:
        """Check if a path should be excluded."""
        parts = path.parts
        for part in parts:
            if part in self.exclude_dirs:
                return True
            # Handle glob-like patterns like *.egg-info
            for excl in self.exclude_dirs:
                if "*" in excl and part.endswith(excl.lstrip("*")):
                    return True
        return False

    def _scan(self) -> Dict[str, float]:
        """Scan project for tracked files and return {rel_path: mtime}."""
        snapshot: Dict[str, float] = {}
        try:
            for root_dir, dirs, files in os.walk(self.project_root):
                root_path = Path(root_dir)
                rel_root = root_path.relative_to(self.project_root)

                if self._should_exclude(rel_root):
                    dirs.clear()
                    continue

                # Prune excluded dirs for os.walk
                dirs[:] = [
                    d for d in dirs
                    if not self._should_exclude(rel_root / d)
                ]

                for fname in files:
                    if not any(fname.endswith(ext) for ext in self.extensions):
                        continue
                    fpath = root_path / fname
                    try:
                        mtime = fpath.stat().st_mtime
                        rel = str(fpath.relative_to(self.project_root)).replace("\\", "/")
                        snapshot[rel] = mtime
                    except (OSError, ValueError):
                        continue
        except OSError:
            pass
        return snapshot

    def take_snapshot(self) -> None:
        """Take initial snapshot of file state."""
        self._snapshot = self._scan()

    def detect_changes(self) -> List[FileChange]:
        """Compare current state to snapshot and return changes.

        Debounces: ignores files that changed within DEBOUNCE_WINDOW.
        """
        current = self._scan()
        now = time.monotonic()
        changes: List[FileChange] = []

        # Modified or created
        for path, mtime in current.items():
            old_mtime = self._snapshot.get(path)
            if old_mtime is None:
                # New file
                last = self._last_change_time.get(path, 0)
                if now - last >= DEBOUNCE_WINDOW:
                    changes.append(FileChange(path=path, change_type="created", mtime=mtime))
                    self._last_change_time[path] = now
            elif mtime != old_mtime:
                # Modified
                last = self._last_change_time.get(path, 0)
                if now - last >= DEBOUNCE_WINDOW:
                    changes.append(FileChange(path=path, change_type="modified", mtime=mtime))
                    self._last_change_time[path] = now

        # Deleted
        for path in self._snapshot:
            if path not in current:
                changes.append(FileChange(path=path, change_type="deleted"))

        # Update snapshot
        self._snapshot = current
        return changes

    @property
    def running(self) -> bool:
        return self._running

    def stop(self) -> None:
        self._running = False


# ═══════════════════════════════════════════════════════════════════════
# 3b. WatchdogFileWatcher — OS-level event-driven watcher (optional)
# ═══════════════════════════════════════════════════════════════════════

if _WATCHDOG_AVAILABLE:
    class _CodegraphEventHandler(FileSystemEventHandler):  # type: ignore[misc]
        """Collect watchdog events into a thread-safe queue."""

        def __init__(
            self,
            project_root: Path,
            extensions: Set[str],
            exclude_dirs: Set[str],
            event_queue: "queue.Queue[FileChange]",
        ) -> None:
            super().__init__()
            self._root = project_root
            self._extensions = extensions
            self._exclude_dirs = exclude_dirs
            self._queue = event_queue
            self._debounce: Dict[str, float] = {}

        def _should_ignore(self, src_path: str) -> bool:
            try:
                rel = Path(src_path).relative_to(self._root)
            except ValueError:
                return True
            # Extension filter
            if not any(str(rel).endswith(ext) for ext in self._extensions):
                return True
            # Directory exclusions
            parts = rel.parts
            for part in parts[:-1]:  # skip the filename itself
                if part in self._exclude_dirs:
                    return True
                for excl in self._exclude_dirs:
                    if "*" in excl and part.endswith(excl.lstrip("*")):
                        return True
            return False

        def _enqueue(self, change_type: str, src_path: str) -> None:
            if self._should_ignore(src_path):
                return
            now = time.monotonic()
            last = self._debounce.get(src_path, 0.0)
            if now - last < DEBOUNCE_WINDOW:
                return
            self._debounce[src_path] = now
            try:
                rel = str(Path(src_path).relative_to(self._root)).replace("\\", "/")
            except ValueError:
                return
            mtime = 0.0
            if change_type != "deleted":
                try:
                    mtime = Path(src_path).stat().st_mtime
                except OSError:
                    return
            self._queue.put(FileChange(path=rel, change_type=change_type, mtime=mtime))

        def on_modified(self, event: "FileSystemEvent") -> None:
            if not event.is_directory:
                self._enqueue("modified", event.src_path)

        def on_created(self, event: "FileSystemEvent") -> None:
            if not event.is_directory:
                self._enqueue("created", event.src_path)

        def on_deleted(self, event: "FileSystemEvent") -> None:
            if not event.is_directory:
                self._enqueue("deleted", event.src_path)

        def on_moved(self, event: "FileSystemEvent") -> None:
            if not event.is_directory:
                self._enqueue("deleted", event.src_path)
                self._enqueue("created", event.dest_path)

    class WatchdogFileWatcher:
        """OS-level event-driven file watcher powered by watchdog.

        Drops the polling overhead entirely; events arrive via inotify /
        FSEvents / ReadDirectoryChangesW.  Public API is identical to
        ``FileWatcher`` so ``ReactiveServer`` uses either transparently.
        """

        def __init__(
            self,
            project_root: Path,
            *,
            interval: float = DEFAULT_POLL_INTERVAL,  # kept for API compat, unused
            extensions: Optional[Set[str]] = None,
            exclude_dirs: Optional[Set[str]] = None,
        ) -> None:
            self.project_root = project_root
            self.interval = interval
            self.extensions = extensions or {".py"}
            self.exclude_dirs = exclude_dirs or {
                ".codegraph", "__pycache__", ".git", ".venv", "venv",
                "node_modules", ".tox", ".mypy_cache", ".pytest_cache",
                "dist", "build", ".eggs", "*.egg-info",
            }
            self._event_queue: "queue.Queue[FileChange]" = queue.Queue()
            self._observer: Optional["_WatchdogObserver"] = None
            self._running = False

        def take_snapshot(self) -> None:
            """Start the watchdog observer (no snapshot needed)."""
            handler = _CodegraphEventHandler(
                self.project_root,
                self.extensions,
                self.exclude_dirs,
                self._event_queue,
            )
            self._observer = _WatchdogObserver()
            self._observer.schedule(handler, str(self.project_root), recursive=True)
            self._observer.start()
            self._running = True

        def detect_changes(self) -> List[FileChange]:
            """Drain the event queue and return accumulated changes."""
            changes: List[FileChange] = []
            try:
                while True:
                    changes.append(self._event_queue.get_nowait())
            except queue.Empty:
                pass
            return changes

        @property
        def running(self) -> bool:
            return self._running

        def stop(self) -> None:
            self._running = False
            if self._observer is not None:
                self._observer.stop()
                self._observer.join(timeout=5)
                self._observer = None


def make_file_watcher(
    project_root: Path,
    *,
    interval: float = DEFAULT_POLL_INTERVAL,
    extensions: Optional[Set[str]] = None,
    exclude_dirs: Optional[Set[str]] = None,
) -> "FileWatcher | WatchdogFileWatcher":
    """Return the best available file watcher for this environment.

    Uses watchdog (OS-level events) when installed; falls back to
    polling-based ``FileWatcher`` otherwise.  Both share the same API
    so callers don't need to branch.
    """
    if _WATCHDOG_AVAILABLE:
        logger.debug("Using watchdog-based file watcher")
        return WatchdogFileWatcher(  # type: ignore[return-value]
            project_root,
            interval=interval,
            extensions=extensions,
            exclude_dirs=exclude_dirs,
        )
    logger.debug("watchdog not installed; using polling file watcher")
    return FileWatcher(
        project_root,
        interval=interval,
        extensions=extensions,
        exclude_dirs=exclude_dirs,
    )


# ═══════════════════════════════════════════════════════════════════════
# 4. Reactive Server — Orchestrator
# ═══════════════════════════════════════════════════════════════════════


@dataclass
class ServerConfig:
    """Configuration for the reactive server."""

    interval: float = DEFAULT_POLL_INTERVAL
    json_mode: bool = False
    quiet: bool = False
    simulate: bool = False
    max_prompts_per_cycle: int = 10


@dataclass
class ReactiveEvent:
    """A single reactive event (one analysis cycle)."""

    changed_files: List[str]
    prompts: List[ReactivePrompt]
    timestamp: str = ""
    cycle: int = 0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "cycle": self.cycle,
            "changed_files": self.changed_files,
            "prompts": [p.to_dict() for p in self.prompts],
            "timestamp": self.timestamp,
        }


class ReactiveServer:
    """The reactive intelligence loop orchestrator.

    Polls for file changes → runs intelligence → generates prompts → writes feedback.
    """

    def __init__(
        self,
        project_root: Path,
        config: Optional[ServerConfig] = None,
    ):
        self.project_root = project_root
        self.config = config or ServerConfig()
        self.watcher = make_file_watcher(
            project_root,
            interval=self.config.interval,
        )
        self.writer = FeedbackWriter(
            project_root,
            json_mode=self.config.json_mode,
            quiet=self.config.quiet,
        )
        self.prompt_engine = PromptEngine()
        self._cycle = 0
        self._events: List[ReactiveEvent] = []

    def _analyze_file(
        self, file_path: str, *, batch_size: int = 1,
    ) -> List[ReactivePrompt]:
        """Run the intelligence loop on a single changed file and generate prompts.

        Adaptive loop compression:
            - small  (batch 1-2): focus only — fast, low overhead
            - medium (batch 3-5): focus + decide
            - large  (batch 6+):  focus + decide + simulate
        """
        from codegraph.utils.formatting import iso_now

        timestamp = iso_now()
        target = file_path

        # Determine analysis depth from batch size
        run_decide = batch_size >= 3
        run_simulate = batch_size >= 6 or self.config.simulate

        # Step 1: Focus context (always)
        focus_dict: Dict[str, Any] = {}
        try:
            from codegraph.copilot_context_builder import focus_context
            focus = focus_context(self.project_root, target)
            focus_dict = focus.to_dict()
        except Exception as exc:
            logger.debug("Focus failed for %s: %s", target, exc)

        # Escalate to decide if focus reveals violations or medium+ smells
        if not run_decide and focus_dict:
            if focus_dict.get("violations"):
                run_decide = True
            smells = focus_dict.get("smells", [])
            if any(s.get("severity") in ("medium", "high", "critical") for s in smells):
                run_decide = True

        # Step 2: Decision (medium+ or escalated)
        decision_dict: Dict[str, Any] = {}
        if run_decide:
            try:
                from codegraph.copilot_intelligence import decide
                decision = decide(self.project_root, target)
                decision_dict = decision.to_dict()
            except Exception as exc:
                logger.debug("Decide failed for %s: %s", target, exc)

            # Escalate to simulate if decision risk is high
            if not run_simulate and decision_dict.get("risk") == "high":
                run_simulate = True

        # Step 3: Simulation (large or escalated)
        simulation_dict: Dict[str, Any] = {}
        deep_sim_dict: Dict[str, Any] = {}
        if run_simulate:
            try:
                from codegraph.copilot_intelligence import _try_simulate, Decision

                if decision_dict:
                    d = Decision(
                        decision_id=decision_dict.get("decision_id", ""),
                        target=target,
                        action=decision_dict.get("action", ""),
                    )
                    simulation_dict = _try_simulate(self.project_root, target, d)
            except Exception as exc:
                logger.debug("Simulation failed for %s: %s", target, exc)

            try:
                from codegraph.copilot_intelligence import _deep_simulate
                from codegraph.copilot_context_builder import focus_context as _fc2

                fc = _fc2(self.project_root, target)
                deep_sim_dict = _deep_simulate(self.project_root, target, fc)
            except Exception as exc:
                logger.debug("Deep simulation failed for %s: %s", target, exc)

        # Step 4: Generate prompts
        prompts = self.prompt_engine.generate(
            target,
            focus=focus_dict,
            decision=decision_dict,
            simulation=simulation_dict,
            deep_sim=deep_sim_dict,
            timestamp=timestamp,
        )

        return prompts[:self.config.max_prompts_per_cycle]

    def run_once(self, changed_files: Optional[List[str]] = None) -> ReactiveEvent:
        """Run one analysis cycle on the given files (or auto-detect).

        Useful for testing or one-shot mode.
        """
        from codegraph.utils.formatting import iso_now

        if changed_files is None:
            changes = self.watcher.detect_changes()
            changed_files = [c.path for c in changes]

        self._cycle += 1
        all_prompts: List[ReactivePrompt] = []

        for fpath in changed_files:
            if not fpath.endswith(".py"):
                continue
            try:
                file_prompts = self._analyze_file(
                    fpath, batch_size=len(changed_files),
                )
                all_prompts.extend(file_prompts)
            except Exception as exc:
                logger.warning("Analysis failed for %s: %s", fpath, exc)

        # Write feedback
        if all_prompts:
            self.writer.write(all_prompts)
            if self.config.json_mode:
                self.writer.write_json(all_prompts)

        event = ReactiveEvent(
            changed_files=changed_files,
            prompts=all_prompts,
            timestamp=iso_now(),
            cycle=self._cycle,
        )
        self._events.append(event)
        return event

    def run_loop(self, max_cycles: int = 0) -> None:
        """Run the polling loop until stopped.

        Args:
            max_cycles: Stop after N cycles. 0 = run forever.
        """
        self.watcher.take_snapshot()
        self.watcher._running = True

        if not self.config.quiet:
            print(f"[codegraph server] Watching {self.project_root} "
                  f"(interval={self.config.interval}s)")

        try:
            while self.watcher.running:
                changes = self.watcher.detect_changes()

                if changes:
                    changed_files = [c.path for c in changes]
                    if not self.config.quiet:
                        print(f"\n[codegraph server] Detected {len(changes)} change(s): "
                              f"{', '.join(changed_files[:5])}")

                    self.run_once(changed_files)

                if max_cycles and self._cycle >= max_cycles:
                    break

                time.sleep(self.watcher.interval)

        except KeyboardInterrupt:
            if not self.config.quiet:
                print("\n[codegraph server] Stopped.")
        finally:
            self.watcher.stop()

    @property
    def events(self) -> List[ReactiveEvent]:
        return list(self._events)

    @property
    def cycle_count(self) -> int:
        return self._cycle
